// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_Ak4_JveBicXP3OcqesNWyxcxPKxbiz0',
    appId: '1:1085536745850:web:f99ee6eb1ac07380d7fec3',
    messagingSenderId: '1085536745850',
    projectId: 'edu-vista-test000',
    authDomain: 'edu-vista-test000.firebaseapp.com',
    storageBucket: 'edu-vista-test000.appspot.com',
    measurementId: 'G-TS0Y6RH1C9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGK-lkXPSlWi0l-2gNU_H2LTRGfTGikUU',
    appId: '1:1085536745850:android:da69fe5300fc030fd7fec3',
    messagingSenderId: '1085536745850',
    projectId: 'edu-vista-test000',
    storageBucket: 'edu-vista-test000.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvomUCwByhoCLlDw0zvl3MtdTMtLamAU0',
    appId: '1:1085536745850:ios:65af24f5086ce7e1d7fec3',
    messagingSenderId: '1085536745850',
    projectId: 'edu-vista-test000',
    storageBucket: 'edu-vista-test000.appspot.com',
    iosBundleId: 'com.example.eduVistaTest',
  );
}
